# Generated by Django 6.0.2 on 2026-02-17 09:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingphoto',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='meeting',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='meetingphoto',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='meetingphoto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
