# Generated by Django 6.0.2 on 2026-02-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0002_rename_uploaded_at_meetingphoto_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='recipient_emails',
            field=models.JSONField(default=list),
        ),
    ]
